enum TokenType {
    LEFT_PAREN, RIGHT_PAREN,
    COMMA, DOT, MINUS, PLUS, SEMICOLON, SLASH, STAR, COLON, ASSIGN, SPREAD,

    // Logical operators
    EQUAL, GREATER, LESS, OR, AND,

    IDENTIFIER, STRING_LIT,

    // Reserved keywords
    VAR, FOR, END, IN, DO, READ, PRINT, BOOL, ASSERT, INT, STRING,

    EOF
}
