enum TokenType {
    LEFT_PAREN, RIGHT_PAREN,
    COMMA, DOT, MINUS, PLUS, SEMICOLON, SLASH, STAR,

    EQUAL, ASSIGN, GREATER, LESS, OR, AND,

    IDENTIFIER, STRING,

    // Reserved keywords
    VAR, FOR, END, IN, DO, READ, PRINT, BOOL, ASSERT, INT,

    EOF
}
